[versions]
ael = "1.0.1-hf"
agp = "8.13.2"
androidxAppcompat = "1.7.1"
androidxCore = "1.18.0"
androidxGridLayout = "1.1.0"
androidxPref = "1.2.1"
androidxTestBenchmark = "1.4.1"
androidxTestEspresso = "3.7.0"
androidxTestJunit = "1.3.0"
androidxTestRunner = "1.7.0"
androidxTestUiautomator = "2.3.0"
kotlin = "2.3.0"
androidxWork = "2.11.2"
leakcanary = "2.14"
material = "1.14.0"

[libraries]
ael-kt = { group = "com.github.mdp43140.ael", name = "ael_kt", version.ref = "ael" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "androidxGridLayout" }
androidx-kt = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-pref-kt = { group = "androidx.preference", name = "preference", version.ref = "androidxPref" }
androidx-benchmark-macroJunit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxTestBenchmark" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxTestUiautomator" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxTestBenchmark" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"  }
